package privacyanalyzer.ui.view.apklist;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Panel;
import com.vaadin.ui.RadioButtonGroup;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import privacyanalyzer.ui.components.ApksGrid;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ApkListDesign extends VerticalLayout {
	protected Panel searchPanel;
	protected TextField searchField;
	protected RadioButtonGroup<java.lang.String> searchOptions;
	protected Button searchButton;
	protected Button analyzeApk;
	protected ApksGrid list;

	public ApkListDesign() {
		Design.read(this);
	}
}
